version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    links:
     - db
    volumes:
     - .:/usr/app
    container_name: node
    command: npm start

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    logging:
      driver: "none"
