version: '3'

services:
  app:
    image: node:12.10.0-alpine
    container_name: notes-taking-server
    ports:
      - '8080:8080'
    links:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "cd /usr/app/ && npm i && npm start"

  db:
    image: mongo
    container_name: notes-taking-database
    ports:
      - '27017:27017'
    logging:
      driver: 'none'
