version: '3'

services:
  app:
    image: node:12.10.0-alpine
    container_name: notebook-server
    ports:
      - '8080:8080'
    links:
      - db
      - redis-auth
      - redis-cache
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "cd /usr/app/ && npm i && npm run dev"

  db:
    image: mongo
    container_name: notebook-database
    ports:
      - '27017:27017'
    logging:
      driver: 'none'

  redis-auth:
    image: redis:alpine
    container_name: notebook-redis-authcontrol
    expose:
      - 6379
    logging:
      driver: 'none'

  redis-cache:
    image: redis:alpine
    container_name: notebook-redis-cache
    expose:
      - 6379
    logging:
      driver: 'none'
